config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('authentication.urls')),
    path('apps/', include('logging_errors.urls')),
    path('api/', include('logging_errors.api.v1.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

logging_errors/models.py
from django.db import models
from django.urls import reverse

from authentication.models import User


class Application(models.Model):
    name = models.CharField(max_length=32)
    token = models.CharField(max_length=128)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app-detail', args=[self.pk])


class Error(models.Model):
    app = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='errors')
    date = models.DateTimeField()
    type = models.CharField(max_length=128)
    message = models.TextField()
    stacktrace = models.TextField()

    def __str__(self):
        return '{},{}'.format(self.type, self.date)

templates/application_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            Application: {{ app_name }}
        </div>
        <div class="col-6">
            Error type: {{ error_type }}
        </div>
            <div class="w-100"></div>
        <div class="col-6">
            Token: {{ app_token }}
        </div>
        <div class="col-4">
            <form action="" method="get">
                <div class="input-group">
                    <select name="type" class="custom-select">
                        <option selected="selected" disabled>Type of error</option>
                            {% for error_type in error_set %}
                                <option value="{{ error_type }}">{{ error_type }}</option>
                            {% endfor %}
                    </select>
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Select</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Type</th>
      <th scope="col">Message</th>
      <th scope="col">Stacktrace</th>
    </tr>
  </thead>
    <tbody>
      {% for error in error_list %}
        <tr>
          <td>{{error.date}}</td>
          <td>{{error.type}}</td>
          <td>{{error.message}}</td>
          <td>{{error.stacktrace}}</td>
         </tr>
      {% endfor %}
    </tbody>
</table>
<div class="paginator">
    {% with request.get_full_path as querystring %}
        <ul class="pagination justify-content-center">
            <!-- Previous page section -->
            {% if error_list.has_previous %}
                {% if 'type' in querystring %}
                    <li class="page-item {% if error_list.number == page %}active{% endif %}">
                        <a class="page-link text-secondary" href="{{ querystring }}&page={{ error_list.previous_page_number }}">Prev</a>
                    </li>
                {% else %}
                    <li class="page-item {% if error_list.number == page %}active{% endif %}">
                        <a class="page-link text-secondary" href="?page={{ error_list.previous_page_number }}">Prev</a>
                    </li>
                {% endif %}
            {% endif %}
            <!-- All pages section -->
            {% for page in error_list.paginator.page_range %}
                {% if error_list.has_next or error_list.has_previous%}
                    {% if 'type' in querystring %}
                        <li class="page-item {% if error_list.number == page %}active{% endif %}">
                            <a class="page-link text-secondary" href="{{ querystring }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if error_list.number == page %}active{% endif %}">
                            <a class="page-link text-secondary" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- Next page section -->
            {% if error_list.has_next %}
                {% if 'type' in querystring %}
                    <li class="page-item {% if error_list.number == page %}active{% endif %}">
                        <a class="page-link text-secondary" href="{{ querystring }}&page={{ error_list.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item {% if error_list.number == page %}active{% endif %}">
                        <a class="page-link text-secondary" href="?page={{ error_list.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    {% endwith %}
</div>

<div id="container">
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
  Highcharts.chart('container', {
      chart: {
          type: 'column'
      },
      title: {
          text: 'Number of errors per day'
      },
      xAxis: {
          categories: {{ date|safe }}
      },
      yAxis: {
          min: 0,
          title: {
              text: 'Count'
          }
	  },
      series: [{
          name: 'number of errors per day',
          data: {{ count_errors }},
          color: 'green'
      }]
  });
</script>
</div>

{% endblock content %}

templates/applications.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 col-xl-4 mx-auto">
        <div class="card card-signin my-5 bg-light text-dark">
          <div class="card-body">
            <h5 class="card-title text-center">Choose application:</h5>
            <div class="btn btn-block bg-light">
                {% for application in application_list %}
                  <a href="{{ application.get_absolute_url }}" class="btn btn-light">{{ application }}</a>
                  <br>
                {% endfor %}
                <br>
            {% if application_list.has_other_pages %}
              <ul class="pagination justify-content-center">
                {% if application_list.has_previous %}
                  <li class="page-item"><a class="page-link text-secondary" href="?page={{ application_list.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item"><span class="page-link text-secondary">&laquo;</span></li>
                {% endif %}
                {% for i in application_list.paginator.page_range %}
                  {% if application_list.number == i %}
                    <li class="active page-item"><span class="page-link text-secondary">{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link text-secondary" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if application_list.has_next %}
                  <li class="page-item"><a class="page-link text-secondary" href="?page={{ application_list.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item"><span class="page-link text-secondary">&raquo;</span></li>
                {% endif %}
              </ul>
            {% endif %}
                <form method="post" action=""> {% csrf_token %}
                  <div class="input-group">
                    <input type="text" class="form-control" name="addnewapp" placeholder="Add new application">
                      <span class="input-group-btn">
                        <button class="btn btn-secondary" type="submit">+</button>
                      </span>
                  </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Logging errors</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Logging errors">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "style.css" %}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-navbar-color" id="navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}"><i class='fas fa-chart-line navbar-brand-color'>Crashlytics</i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive">
            <ul class="navbar-url-color navbar-nav">
                {% if user.is_authenticated %}
                    <div class="username-cl">
                        <li class="nav-link">{{ user.get_username }}</li>
                    </div>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>